package com.dtakac.aux_remote.common

// FRAGMENT KEYS
const val FRAGMENT_CONNECT = "FRAGMENT_CONNECT"
const val FRAGMENT_PAGER = "FRAGMENT_PAGER"

// PREFS KEYS
const val PREFS_USER_ID = "PREFS_USER_ID"
const val PREFS_IP_INPUT = "PREFS_IP_INPUT"
const val PREFS_PORT_INPUT = "PREFS_PORT_INPUT"

// CLIENT KEYS
const val CLIENT_MAC = "CLIENT_MAC_ADDRESS"