package com.dtakac.aux_remote.common.constants

// PREFS KEYS
const val PREFS_USER_ID = "PREFS_USER_ID"
const val PREFS_IP_INPUT = "PREFS_IP_INPUT"
const val PREFS_PORT_INPUT = "PREFS_PORT_INPUT"

// CLIENT KEYS
const val CLIENT_MAC = "CLIENT_MAC_ADDRESS"
const val CLIENT_QUEUE = "CLIENT_QUEUE"
const val CLIENT_REQUEST_SONGS = "CLIENT_SONGS_REQUEST"
const val CLIENT_REQUEST_QUEUE = "CLIENT_QUEUE_REQUEST"
const val CLIENT_REQUEST_PLAYING = "CLIENT_NOW_PLAYING_REQUEST"

// SERVER KEYS
const val SERVER_BROADCAST_END = "SERVER_BROADCAST_ENDED"
const val SERVER_SONG_LIST = "SERVER_SONG_LIST"
const val SERVER_QUEUE_LIST = "SERVER_QUEUE_LIST"
const val SERVER_ENQUEUED = "SERVER_ENQUEUED"
const val SERVER_MOVE_UP = "SERVER_MOVE_UP"
const val SERVER_NOW_PLAYING = "SERVER_NOW_PLAYING"

// OTHER
const val EMPTY_STRING = ""